# Generated by Django 6.0.3 on 2026-04-22 13:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Nombre de ícono (ej: 'pipe', 'gear')", max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('material_type', models.CharField(choices=[('polyurethane', 'Poliuretano'), ('rubber', 'Caucho'), ('polyurethane_rubber', 'Poliuretano/Caucho')], max_length=30)),
                ('hardness', models.CharField(blank=True, help_text='Ej: 80 Shore A', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('color_options', models.CharField(blank=True, help_text='Colores disponibles separados por coma', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomOrderRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('part_description', models.TextField(verbose_name='Descripción de la pieza')),
                ('vehicle_make', models.CharField(max_length=100, verbose_name='Marca vehículo')),
                ('vehicle_model', models.CharField(max_length=100, verbose_name='Modelo vehículo')),
                ('vehicle_year', models.CharField(blank=True, max_length=10, verbose_name='Año vehículo')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='custom_orders/references/')),
                ('reference_file', models.FileField(blank=True, help_text='Plano, STL, o cualquier referencia', null=True, upload_to='custom_orders/files/')),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('reviewing', 'En revisión'), ('quoted', 'Cotizado'), ('approved', 'Aprobado'), ('in_production', 'En producción'), ('completed', 'Completado'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('preferred_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.material')),
            ],
            options={
                'verbose_name': 'Pedido personalizado',
                'verbose_name_plural': 'Pedidos personalizados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(default='Chile', max_length=50)),
                ('payment_method', models.CharField(choices=[('webpay', 'WebPay / Transbank'), ('mercadopago', 'MercadoPago'), ('bank_transfer', 'Transferencia bancaria')], max_length=20)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('payment_id', models.CharField(blank=True, help_text='ID transacción del gateway', max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notification_method', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('both', 'WhatsApp + Email')], default='email', max_length=10)),
                ('status', models.CharField(choices=[('pending_payment', 'Pago pendiente'), ('paid', 'Pagado'), ('in_production', 'En producción'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending_payment', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sku', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('compatible_vehicles', models.TextField(blank=True, help_text='Marcas/modelos compatibles, uno por línea')),
                ('width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('height_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('depth_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio base')),
                ('custom_price_note', models.CharField(blank=True, help_text='Nota sobre precio personalizado', max_length=200)),
                ('model_3d_file', models.FileField(blank=True, help_text='Archivo .glb o .gltf para vista 3D', null=True, upload_to='models_3d/')),
                ('model_3d_url', models.URLField(blank=True, help_text='URL externa del modelo 3D')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/thumbnails/')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('on_request', 'Solo a pedido')], default='active', max_length=15)),
                ('is_featured', models.BooleanField(default=False)),
                ('min_order_qty', models.PositiveIntegerField(default=1, help_text='Cantidad mínima de pedido')),
                ('production_days', models.PositiveIntegerField(default=7, help_text='Días de producción estimados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category')),
                ('materials', models.ManyToManyField(blank=True, to='store.material')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=50)),
                ('size_label', models.CharField(blank=True, help_text="Ej: 'M', '25mm', 'Tipo A'", max_length=50)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, help_text='Ajuste de precio (+/-)', max_digits=8)),
                ('stock', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_sku', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custom_notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('custom_notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productvariant')),
            ],
        ),
    ]
